"""initial schema

Revision ID: f6708ea6b1f4
Revises:
Create Date: 2026-06-05 16:36:09.947028+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'f6708ea6b1f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS app")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_types',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='app'
    )
    op.create_table('class_types',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='app'
    )
    op.create_table('contacts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('wa_id', sa.String(length=30), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('profile_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_saved', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('lead_sources',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='app'
    )
    op.create_table('marketing_campaigns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=True),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('start_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('end_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_campaigns_external_id', 'marketing_campaigns', ['external_id'], unique=False, schema='app', postgresql_where='external_id IS NOT NULL')
    op.create_index('idx_campaigns_platform_dates', 'marketing_campaigns', ['platform', 'start_at', 'end_at'], unique=False, schema='app')
    op.create_table('membership_plans',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('duration_value', sa.Integer(), nullable=False),
    sa.Column('duration_unit', sa.String(length=10), nullable=False),
    sa.Column('class_limit', sa.Integer(), nullable=True),
    sa.Column('fixed_time_slot', sa.Boolean(), nullable=False),
    sa.Column('max_sessions_per_day', sa.Integer(), nullable=True),
    sa.Column('max_sessions_per_week', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("duration_unit IN ('day','week','month')", name='ck_duration_unit'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('people',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('wa_id', sa.String(length=100), nullable=True),
    sa.Column('profile_picture_path', sa.String(length=255), nullable=True),
    sa.Column('profile_picture_uploaded_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_people_email', 'people', ['email'], unique=False, schema='app', postgresql_where='email IS NOT NULL')
    op.create_index('idx_people_phone', 'people', ['phone_number'], unique=False, schema='app', postgresql_where='phone_number IS NOT NULL')
    op.create_index('idx_people_wa_id', 'people', ['wa_id'], unique=False, schema='app', postgresql_where='wa_id IS NOT NULL')
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='app'
    )
    op.create_table('seat_types',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='app'
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('session', sa.String(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('last_active_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('venues',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('capacity > 0', name='ck_venue_capacity'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('webhook_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('x_request_id', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('processed', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('whatsapp_templates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('template_namespace', sa.String(length=100), nullable=False),
    sa.Column('template_language', sa.String(length=10), nullable=False),
    sa.Column('template_status', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('meta_template_id', sa.String(length=64), nullable=True),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('uq_whatsapp_templates_name_language', 'whatsapp_templates', ['template_name', 'template_language'], unique=True, schema='app')
    op.create_table('accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['app.people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='app'
    )
    op.create_table('asset_models',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_type_id', sa.BigInteger(), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('maintenance_interval_days', sa.Integer(), nullable=True),
    sa.Column('maintenance_interval_classes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_type_id'], ['app.asset_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('class_templates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('class_type_id', sa.BigInteger(), nullable=False),
    sa.Column('venue_id', sa.BigInteger(), nullable=False),
    sa.Column('default_capacity', sa.Integer(), nullable=True),
    sa.Column('default_duration_min', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time_local', sa.Time(), nullable=False),
    sa.Column('instructor_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('default_duration_min BETWEEN 15 AND 240', name='ck_duration_range'),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name='ck_weekday_range'),
    sa.ForeignKeyConstraint(['class_type_id'], ['app.class_types.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['app.people.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['app.venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('communications_opt_in',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('granted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("channel IN ('whatsapp','email','sms')", name='ck_communication_channel'),
    sa.ForeignKeyConstraint(['person_id'], ['app.people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_optin_active', 'communications_opt_in', ['channel', 'granted_at'], unique=False, schema='app', postgresql_where='revoked_at IS NULL')
    op.create_index('idx_optin_person_channel', 'communications_opt_in', ['person_id', 'channel'], unique=False, schema='app')
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expiration_timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['app.contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('form_submissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('form_id', sa.String(length=80), nullable=True),
    sa.Column('form_name', sa.String(length=120), nullable=True),
    sa.Column('submitted_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('landing_url', sa.Text(), nullable=True),
    sa.Column('referrer_url', sa.Text(), nullable=True),
    sa.Column('utm_source', sa.String(length=80), nullable=True),
    sa.Column('utm_medium', sa.String(length=80), nullable=True),
    sa.Column('utm_campaign', sa.String(length=120), nullable=True),
    sa.Column('utm_term', sa.String(length=120), nullable=True),
    sa.Column('utm_content', sa.String(length=120), nullable=True),
    sa.Column('gclid', sa.String(length=200), nullable=True),
    sa.Column('fbclid', sa.String(length=200), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['app.people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_form_submissions_campaign', 'form_submissions', ['utm_campaign', 'submitted_at'], unique=False, schema='app')
    op.create_index('idx_form_submissions_person', 'form_submissions', ['person_id', 'submitted_at'], unique=False, schema='app')
    op.create_index('idx_form_submissions_source', 'form_submissions', ['utm_source', 'submitted_at'], unique=False, schema='app')
    op.create_table('person_roles',
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['app.people.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['app.roles.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'role_id'),
    schema='app'
    )
    op.create_table('seats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('venue_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('col_number', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('seat_type_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['seat_type_id'], ['app.seat_types.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['app.venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'label', name='uq_venue_seat_label'),
    schema='app'
    )
    op.create_table('whatsapp_threads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('wa_id', sa.String(length=100), nullable=True),
    sa.Column('phone_e164', sa.String(length=32), nullable=True),
    sa.Column('last_inbound_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_outbound_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_message_snippet', sa.Text(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['app.people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', name='uq_wa_thread_person'),
    schema='app'
    )
    op.create_index('idx_wa_threads_last_activity', 'whatsapp_threads', ['last_inbound_at', 'last_outbound_at'], unique=False, schema='app')
    op.create_index('idx_wa_threads_phone', 'whatsapp_threads', ['phone_e164'], unique=False, schema='app', postgresql_where='phone_e164 IS NOT NULL')
    op.create_index('idx_wa_threads_wa_id', 'whatsapp_threads', ['wa_id'], unique=False, schema='app', postgresql_where='wa_id IS NOT NULL')
    op.create_table('assets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_model_id', sa.BigInteger(), nullable=False),
    sa.Column('serial_number', sa.String(length=120), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('retired_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('in_service','maintenance','retired')", name='ck_asset_status'),
    sa.ForeignKeyConstraint(['asset_model_id'], ['app.asset_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number'),
    schema='app'
    )
    op.create_index('idx_assets_status', 'assets', ['status', 'asset_model_id'], unique=False, schema='app')
    op.create_table('class_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('class_type_id', sa.BigInteger(), nullable=False),
    sa.Column('venue_id', sa.BigInteger(), nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=True),
    sa.Column('instructor_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('start_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('scheduled','canceled','completed')", name='ck_session_status'),
    sa.CheckConstraint('capacity > 0', name='ck_session_capacity'),
    sa.ForeignKeyConstraint(['class_type_id'], ['app.class_types.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['app.people.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['app.class_templates.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['app.venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_sessions_instructor', 'class_sessions', ['instructor_id', 'start_at'], unique=False, schema='app')
    op.create_index('idx_sessions_template', 'class_sessions', ['template_id', 'start_at'], unique=False, schema='app')
    op.create_index('idx_sessions_time', 'class_sessions', ['start_at', 'venue_id'], unique=False, schema='app')
    op.create_table('leads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('owner_account_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('converted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('migrated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('new','contacted','qualified','converted','lost','disqualified')", name='ck_lead_status'),
    sa.ForeignKeyConstraint(['owner_account_id'], ['app.accounts.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['app.people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['app.lead_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_leads_legacy_id', 'leads', ['legacy_id'], unique=False, schema='app', postgresql_where='legacy_id IS NOT NULL')
    op.create_index('idx_leads_person_status', 'leads', ['person_id', 'status'], unique=False, schema='app')
    op.create_index('idx_leads_source_created', 'leads', ['source_id', 'created_at'], unique=False, schema='app')
    op.create_index('idx_leads_status_updated', 'leads', ['status', 'updated_at'], unique=False, schema='app')
    op.create_index('uq_lead_active_per_source', 'leads', ['person_id', 'source_id'], unique=True, schema='app', postgresql_where="status IN ('new','contacted','qualified')")
    op.create_table('membership_subscriptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('start_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active','expired','canceled','pending')", name='ck_subscription_status'),
    sa.ForeignKeyConstraint(['created_by'], ['app.accounts.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['app.people.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['app.membership_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_subscriptions_active', 'membership_subscriptions', ['status', 'end_at'], unique=False, schema='app', postgresql_where="status = 'active'")
    op.create_index('idx_subscriptions_person', 'membership_subscriptions', ['person_id', 'status', 'end_at'], unique=False, schema='app')
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('wa_message_id', sa.String(length=100), nullable=True),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.String(length=30), nullable=False),
    sa.Column('message_type', sa.String(length=30), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('template_id', sa.BigInteger(), nullable=True),
    sa.Column('context_message_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_processed', sa.SmallInteger(), nullable=True),
    sa.Column('processed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_temp', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['app.contacts.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['app.conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.execute("""
    CREATE OR REPLACE FUNCTION app.notify_whatsapp_message() RETURNS trigger AS $$
    BEGIN
      PERFORM pg_notify(
        'whatsapp_events',
        json_build_object(
          'type', 'message',
          'id', NEW.id,
          'conversation_id', NEW.conversation_id,
          'contact_id', NEW.contact_id,
          'direction', NEW.direction
        )::text
      );
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE TRIGGER trg_notify_whatsapp_message
    AFTER INSERT ON app.messages
    FOR EACH ROW EXECUTE FUNCTION app.notify_whatsapp_message();
    """)
    op.create_table('asset_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('performed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("event_type IN ('maintenance','repair','inspection','incident')", name='ck_event_type'),
    sa.ForeignKeyConstraint(['asset_id'], ['app.assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['app.accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_asset_events_asset', 'asset_events', ['asset_id', 'performed_at'], unique=False, schema='app')
    op.create_table('asset_seat_assignments',
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('seat_id', sa.BigInteger(), nullable=False),
    sa.Column('unassigned_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('unassigned_at IS NULL OR unassigned_at > assigned_at', name='ck_assignment_dates'),
    sa.ForeignKeyConstraint(['asset_id'], ['app.assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_id'], ['app.seats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'assigned_at'),
    schema='app'
    )
    op.create_index('uq_asset_active_assignment', 'asset_seat_assignments', ['asset_id'], unique=True, schema='app', postgresql_where='unassigned_at IS NULL')
    op.create_index('uq_seat_active_asset', 'asset_seat_assignments', ['seat_id'], unique=True, schema='app', postgresql_where='unassigned_at IS NULL')
    op.create_table('lead_attributions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('utm_source', sa.String(length=80), nullable=True),
    sa.Column('utm_medium', sa.String(length=80), nullable=True),
    sa.Column('utm_campaign', sa.String(length=120), nullable=True),
    sa.Column('utm_term', sa.String(length=120), nullable=True),
    sa.Column('utm_content', sa.String(length=120), nullable=True),
    sa.Column('landing_url', sa.Text(), nullable=True),
    sa.Column('click_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('referrer_url', sa.Text(), nullable=True),
    sa.Column('gclid', sa.String(length=200), nullable=True),
    sa.Column('fbclid', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['app.marketing_campaigns.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['app.leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_lead_attr_campaign', 'lead_attributions', ['campaign_id'], unique=False, schema='app')
    op.create_index('idx_lead_attr_lead', 'lead_attributions', ['lead_id'], unique=False, schema='app')
    op.create_index('idx_lead_attr_utm', 'lead_attributions', ['utm_source', 'utm_medium', 'utm_campaign'], unique=False, schema='app')
    op.create_table('lead_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('event_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("event_type IN ('message_in','message_out','form_submit','status_change','reservation','payment_attempt','note','migration')", name='ck_lead_event_type'),
    sa.ForeignKeyConstraint(['created_by'], ['app.accounts.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['app.leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_lead_events_lead_at', 'lead_events', ['lead_id', 'event_at'], unique=False, schema='app')
    op.create_index('idx_lead_events_type', 'lead_events', ['event_type', 'event_at'], unique=False, schema='app')
    op.create_table('media',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('media_type', sa.String(length=30), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('media_url', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('downloaded', sa.SmallInteger(), nullable=True),
    sa.Column('download_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('download_failed', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['app.messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('message_statuses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['app.messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('subscription_id', sa.BigInteger(), nullable=True),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=120), nullable=True),
    sa.Column('external_reference', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('COMPLETED','PENDING','FAILED','REFUNDED')", name='ck_payments_status'),
    sa.ForeignKeyConstraint(['person_id'], ['app.people.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['app.accounts.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['app.membership_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('idx_payments_person_paidat', 'payments', ['person_id', 'paid_at'], unique=False, schema='app')
    op.create_index('idx_payments_status_paidat', 'payments', ['status', 'paid_at'], unique=False, schema='app')
    op.create_index('idx_payments_subscription', 'payments', ['subscription_id', 'paid_at'], unique=False, schema='app')
    op.create_index('uq_payments_provider_payment_id', 'payments', ['provider_payment_id'], unique=True, schema='app', postgresql_where='provider_payment_id IS NOT NULL')
    op.create_table('reservations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('seat_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reserved_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('checkin_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('checkout_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('waitlist_position', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.CheckConstraint("source IN ('manual','standing','override')", name='ck_reservation_source'),
    sa.CheckConstraint("status IN ('reserved','waitlisted','canceled','checked_in','no_show')", name='ck_reservation_status'),
    sa.ForeignKeyConstraint(['person_id'], ['app.people.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['app.seats.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['app.class_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'person_id', name='uq_session_person'),
    schema='app'
    )
    op.create_index('idx_reservations_person', 'reservations', ['person_id', 'reserved_at'], unique=False, schema='app')
    op.create_index('idx_reservations_session', 'reservations', ['session_id', 'status'], unique=False, schema='app')
    op.create_index('uq_reservations_seat_once', 'reservations', ['session_id', 'seat_id'], unique=True, schema='app', postgresql_where="seat_id IS NOT NULL AND status IN ('reserved','checked_in')")
    op.create_table('standing_bookings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('subscription_id', sa.BigInteger(), nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=False),
    sa.Column('seat_id', sa.BigInteger(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active','paused','canceled')", name='ck_standing_booking_status'),
    sa.ForeignKeyConstraint(['person_id'], ['app.people.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['app.seats.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['app.membership_subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['app.class_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('standing_booking_exceptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('standing_booking_id', sa.BigInteger(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('new_session_id', sa.BigInteger(), nullable=True),
    sa.Column('new_seat_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("action IN ('skip','reschedule')", name='ck_exception_action'),
    sa.ForeignKeyConstraint(['new_seat_id'], ['app.seats.id'], ),
    sa.ForeignKeyConstraint(['new_session_id'], ['app.class_sessions.id'], ),
    sa.ForeignKeyConstraint(['standing_booking_id'], ['app.standing_bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('standing_booking_id', 'session_date', name='uq_standing_booking_date'),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_notify_whatsapp_message ON app.messages")
    op.execute("DROP FUNCTION IF EXISTS app.notify_whatsapp_message()")
    op.drop_table('standing_booking_exceptions', schema='app')
    op.drop_table('standing_bookings', schema='app')
    op.drop_index('uq_reservations_seat_once', table_name='reservations', schema='app', postgresql_where="seat_id IS NOT NULL AND status IN ('reserved','checked_in')")
    op.drop_index('idx_reservations_session', table_name='reservations', schema='app')
    op.drop_index('idx_reservations_person', table_name='reservations', schema='app')
    op.drop_table('reservations', schema='app')
    op.drop_index('uq_payments_provider_payment_id', table_name='payments', schema='app', postgresql_where='provider_payment_id IS NOT NULL')
    op.drop_index('idx_payments_subscription', table_name='payments', schema='app')
    op.drop_index('idx_payments_status_paidat', table_name='payments', schema='app')
    op.drop_index('idx_payments_person_paidat', table_name='payments', schema='app')
    op.drop_table('payments', schema='app')
    op.drop_table('message_statuses', schema='app')
    op.drop_table('media', schema='app')
    op.drop_index('idx_lead_events_type', table_name='lead_events', schema='app')
    op.drop_index('idx_lead_events_lead_at', table_name='lead_events', schema='app')
    op.drop_table('lead_events', schema='app')
    op.drop_index('idx_lead_attr_utm', table_name='lead_attributions', schema='app')
    op.drop_index('idx_lead_attr_lead', table_name='lead_attributions', schema='app')
    op.drop_index('idx_lead_attr_campaign', table_name='lead_attributions', schema='app')
    op.drop_table('lead_attributions', schema='app')
    op.drop_index('uq_seat_active_asset', table_name='asset_seat_assignments', schema='app', postgresql_where='unassigned_at IS NULL')
    op.drop_index('uq_asset_active_assignment', table_name='asset_seat_assignments', schema='app', postgresql_where='unassigned_at IS NULL')
    op.drop_table('asset_seat_assignments', schema='app')
    op.drop_index('idx_asset_events_asset', table_name='asset_events', schema='app')
    op.drop_table('asset_events', schema='app')
    op.drop_table('messages', schema='app')
    op.drop_index('idx_subscriptions_person', table_name='membership_subscriptions', schema='app')
    op.drop_index('idx_subscriptions_active', table_name='membership_subscriptions', schema='app', postgresql_where="status = 'active'")
    op.drop_table('membership_subscriptions', schema='app')
    op.drop_index('uq_lead_active_per_source', table_name='leads', schema='app', postgresql_where="status IN ('new','contacted','qualified')")
    op.drop_index('idx_leads_status_updated', table_name='leads', schema='app')
    op.drop_index('idx_leads_source_created', table_name='leads', schema='app')
    op.drop_index('idx_leads_person_status', table_name='leads', schema='app')
    op.drop_index('idx_leads_legacy_id', table_name='leads', schema='app', postgresql_where='legacy_id IS NOT NULL')
    op.drop_table('leads', schema='app')
    op.drop_index('idx_sessions_time', table_name='class_sessions', schema='app')
    op.drop_index('idx_sessions_template', table_name='class_sessions', schema='app')
    op.drop_index('idx_sessions_instructor', table_name='class_sessions', schema='app')
    op.drop_table('class_sessions', schema='app')
    op.drop_index('idx_assets_status', table_name='assets', schema='app')
    op.drop_table('assets', schema='app')
    op.drop_index('idx_wa_threads_wa_id', table_name='whatsapp_threads', schema='app', postgresql_where='wa_id IS NOT NULL')
    op.drop_index('idx_wa_threads_phone', table_name='whatsapp_threads', schema='app', postgresql_where='phone_e164 IS NOT NULL')
    op.drop_index('idx_wa_threads_last_activity', table_name='whatsapp_threads', schema='app')
    op.drop_table('whatsapp_threads', schema='app')
    op.drop_table('seats', schema='app')
    op.drop_table('person_roles', schema='app')
    op.drop_index('idx_form_submissions_source', table_name='form_submissions', schema='app')
    op.drop_index('idx_form_submissions_person', table_name='form_submissions', schema='app')
    op.drop_index('idx_form_submissions_campaign', table_name='form_submissions', schema='app')
    op.drop_table('form_submissions', schema='app')
    op.drop_table('conversations', schema='app')
    op.drop_index('idx_optin_person_channel', table_name='communications_opt_in', schema='app')
    op.drop_index('idx_optin_active', table_name='communications_opt_in', schema='app', postgresql_where='revoked_at IS NULL')
    op.drop_table('communications_opt_in', schema='app')
    op.drop_table('class_templates', schema='app')
    op.drop_table('asset_models', schema='app')
    op.drop_table('accounts', schema='app')
    op.drop_index('uq_whatsapp_templates_name_language', table_name='whatsapp_templates', schema='app')
    op.drop_table('whatsapp_templates', schema='app')
    op.drop_table('webhook_logs', schema='app')
    op.drop_table('venues', schema='app')
    op.drop_table('sessions', schema='app')
    op.drop_table('seat_types', schema='app')
    op.drop_table('roles', schema='app')
    op.drop_index('idx_people_wa_id', table_name='people', schema='app', postgresql_where='wa_id IS NOT NULL')
    op.drop_index('idx_people_phone', table_name='people', schema='app', postgresql_where='phone_number IS NOT NULL')
    op.drop_index('idx_people_email', table_name='people', schema='app', postgresql_where='email IS NOT NULL')
    op.drop_table('people', schema='app')
    op.drop_table('membership_plans', schema='app')
    op.drop_index('idx_campaigns_platform_dates', table_name='marketing_campaigns', schema='app')
    op.drop_index('idx_campaigns_external_id', table_name='marketing_campaigns', schema='app', postgresql_where='external_id IS NOT NULL')
    op.drop_table('marketing_campaigns', schema='app')
    op.drop_table('lead_sources', schema='app')
    op.drop_table('contacts', schema='app')
    op.drop_table('class_types', schema='app')
    op.drop_table('asset_types', schema='app')
    # ### end Alembic commands ###
